import { Geist, Geist_Mono, Syne, Syne_Tactile } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const tactile = Syne_Tactile({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-tactile",
});
const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-syne",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`   ${syne.variable} h-full antialiased`}>
      <body className="h-full  flex flex-col gap-10">
        <NavBar />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
